/**
 * Pentagon numbers
 *
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
 *
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
 *
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised;
 * what is the value of D?
 */


function solution() {
    let pentagonalNumbers = [];
    let target = 0;

    function generateNextPentagonalNumber(n) {
        return n * (3 * n - 1) / 2;
    }

    function findPairPentagonals(target) {
        let memo = {};
        let status = false;
        let value = 0;

        for (let j = 0; j < pentagonalNumbers.length; j++) {
            memo[pentagonalNumbers[j]] = true;
            let diff = target - pentagonalNumbers[j];
            if (memo[diff] && memo[pentagonalNumbers[j] - diff]) {
                value = pentagonalNumbers[j] - diff;
                status = true;
                break;
            }
        }

        return value;
    }

    let i = 1
    while (target < 1) {
        let currentPentagon = generateNextPentagonalNumber(i);
        pentagonalNumbers.push(currentPentagon);

        let result = findPairPentagonals(currentPentagon);

        if (result) {
            target = result
        }

        i++;
    }

    return target;
}

let r = solution();
console.log(r); // 5482660 // 1560090 7042750 8602840

